# -*- coding: utf-8 -*-
"""LabReport.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13R2808r8cTR5HQjQogyKFYx1TEK-uNdB

# Lab 1: Data Cleaning and Preprocessing with Python
"""

import pandas as pd

data1 = {
    "ID"  :[1,2,3,4,5,6,7],
    "name": ["Radha", "Krishna", "Hari", "Shyamsundar", "Hanuman", "Ram", "Sita"],
    "age": [20, 25, 30, 35, 40, 45, 50],
    "gender": ["F", "M", "M", "M", "M", "M", "F"]
}

df1=pd.DataFrame(data1)

print(df1)

print(df1.head())

data2 = {
    "ID":[8,9,10,11,12],
    "name": ["Gauri", "Sanker", "Ganesh", "Gopi", "Premanand"],
    "age": [20, 25, 30, 35, 40],
    "gender": ["F", "M", "M","F", "M"]
}

df2=pd.DataFrame(data2)

print(df2)

print(df2.head())

print(df2.tail())

print(df2.describe)

print(df2.info)

print(df2.shape)

data3 = {
    "ID":[8,9,10,11,12,8,9],
    "name": ["Gauri", "Sanker", "Ganesh", "Gopi", "Premanand","Gauri","Sanker"],
    "age": [20, 25, 30, 35, 40,20,25],
    "gender": ["F", "M", "M","F", "M","F","M"]
}

df3=pd.DataFrame(data3)

print(df3.drop_duplicates(inplace=True))

print(df3)

merged_df=pd.merge(df1,df2,on="ID")
print(merged_df)

merged_df=pd.merge(df1,df2,on="age")
print(merged_df)

merged_df=pd.merge(df1,df2,on="gender")
print(merged_df)

import pandas as pd
df4=pd.read_csv("Iris.csv")
df4.head()

print(df4.head())

df4.tail()

df4.describe()

df4.info()

df5=pd.read_csv("Titanic-Dataset.csv")

df5.head()

df5.tail()

df5.info()

df5.describe()

df5.rename(columns={'PassemgerIf': 'Id'}, inplace=True)

hi=df4.drop_duplicates(inplace=True)
print(hi)

hello=df5.drop_duplicates(inplace=True)
print(hello)

# corelation between Survived and Age
correlation=df5['Survived'].corr(df5['Age'])
print(correlation)

# Data Visualization